nuxt.config.ts
package-lock.json
package.json

Added plausible connection to collect website usage data.

Added plausible analytics

---

content/1.sidebase/1.welcome/2.features.md
data/features.ts

doc: Update sidebase features page to fix typo

---

components/landing/Module.vue
layouts/Landing.vue

Fixed new modules section to look good in light mode

---

kubernetes/helm/values-sidebase-docs.yml

increase resources

---

components/landing/TestimonialsSection.vue
content/0.index.md
layouts/Landing.vue

added enterprise section and updated landing annoucement

---

app.config.ts
components/landing/ModulesSection.vue

Added `nuxt-prisma` to list of modules

---

app.vue

fix: improved container padding

---

app.config.ts

Added imprint

---

app.config.ts
components/content/BrandingText.vue
content/0.index.md
content/6.blog/1.index.md
content/6.blog/_dir.yml
content/6.blog/posts/0.index.md
content/6.blog/posts/_dir.yml
content/7.blog-link/1.Posts.md
layouts/Landing.vue
nuxt.config.ts
package-lock.json
package.json

feat: Added Animations, fixed landing page loading error

---

.drone.yml
kubernetes/helm/helmsman.yml
kubernetes/helm/values-sidebase-docs.yml
nuxt.config.ts

Fixed CD to inject Env Variables correctly

---

package-lock.json
package.json

Downgraded Docus to v1.1.3 due to breaking changes

---

public/sitemap.xml

Added sitemap

---

public/sitemap.xml

Updated sitemap

---

components/landing/terminal/Terminal.vue
layouts/Landing.vue

Closes https://github.com/sidebase/orga/issues/7
Checklist:

Fixes for landing page

---

README.md

update readme md
Closes # .
Checklist:

changed “der” to “the”

---

app.config.ts
components/docs/ModulesBar.vue

Add nuxt pdf to modules bar

---

components/docs/ModulesBar.vue
components/docs/ModulesBarLink.vue
components/landing/ModulesSection.vue
content/6.nuxt-pdf/_dir.yml

fix: added light mode support to the modules bar

---

content/2.nuxt-auth/6.ressources/1.index.md
public/sitemap.xml

chore: updated sitemap

---

components/docs/ModulesBar.vue
layouts/module.vue

feat: improved modules bar to feel more smooth

---

components/docs/ModulesBarLink.vue
data/versions.ts

fix: small versioning fixes

---

app.config.ts

fix: Update Link to jobs page

---

data/testimonials.ts

fix: Updated broken images on Landing Page

---

components/docs/ModulesBar.vue
content/50.blog/posts/6-reasons-to-follow-sidebase.md
layouts/module.vue

chore: Remove hard coded version banner and cleanup

---

src/nuxt-auth/resources/errors.md

chore: Add redirect for error reference page

---

.vitepress/config.mts
.vitepress/head.ts

fix: do not include nuxt-auth links inside sitemap

---

.vitepress/head.ts
package.json
pnpm-lock.yaml

chore: add plausible site analytics

---

.github/workflows/ci.yaml
.github/workflows/deploy-docs.yaml

fix: update nodejs versions in CI pipeline
